version: "3.4"

services:
  sta.web-develop:
    container_name: sta-web-develop
    build:
      context: .
      dockerfile: STA.Web/Dockerfile.dev
    volumes:
      - ./STA.Web:/app
      - "/app/node_modules"
    ports:
      - 8000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - APP_ENV=develop
    profiles:
      - develop
  sta.web-staging:
    container_name: sta-web-staging
    build:
      context: .
      dockerfile: STA.Web/Dockerfile.stage
    ports:
      - 8000:80
    profiles:
      - staging
  sta.web:
    container_name: sta-web
    build:
      context: .
      dockerfile: STA.Web/Dockerfile
    ports:
      - 8000:80
    profiles:
      - production
  sta.node:
    container_name: sta-node
    build:
      context: .
      dockerfile: STA.Node/dockerfile
    volumes:
      - ./STA.Node:/node/app
      - "/node/app/node_modules"
    ports:
      - 8811:3333
    profiles:
      - production
  sta.node-staging:
    container_name: sta-node-staging
    build:
      context: .
      dockerfile: STA.Node/dockerfile.stage
    volumes:
      - ./STA.Node:/node/app
      - "/node/app/node_modules"
    ports:
      - 8811:3333
    profiles:
      - staging
  sta.node-develop:
    container_name: sta-node-develop
    build:
      context: .
      dockerfile: STA.Node/dockerfile.dev
    volumes:
      - ./STA.Node:/node/app
      - "/node/app/node_modules"
    ports:
      - 8811:3333
    environment: 
      - DOCUSIGN_INTEGRATION=${DOCUSIGN_INTEGRATION}
      - DOCUSIGN_SECRET=${DOCUSIGN_SECRET}
    profiles:
      - develop
