version: '3.4'

services:
  sta.api:
    image: ${DOCKER_REGISTRY-}staapi
    build:
      context: .
      dockerfile: STA.Api/Dockerfile
    ports:
      - "8080:80"
      - "4430:443"
    environment:      
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=certpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  sta.web:
    image: ${DOCKER_REGISTRY-}staweb
    build:
      context: .
      dockerfile: STA.Web/Dockerfile
    ports:
      - "8081:80"
      - "4431:443"
    environment:      
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=certpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - StaApiEndpoint=https://sta.api/
    volumes:
      - ~/.aspnet/https:/https:ro