 # Docker Image which is used as foundation to create
# a custom Docker Image with this Dockerfile
FROM node:13.12.0-alpine
 
WORKDIR "/app"
ENV PATH /app/node_modules/.bin:$PATH
COPY STA.Web/package.json ./
COPY STA.Web/package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
 
COPY STA.Web/. ./
# Copies everything over to Docker environment
 
# Uses port which is used by the actual application
EXPOSE 3000
 
# Finally runs the application
CMD [ "npm", "run","start:develop"]